spring:
  batch:
    job:
      names: ${job.name:helloWorldJob}
#      ???? ?? ??
    jdbc:
      initialize-schema: ALWAYS
#      spring batch ?? db
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/batch?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    driver-class-name:
    username: lldj
    password: lldj123414
  jpa:
    show-sql: true