spring:
  profiles:
    active : dev
  batch:
    job:
      names: ${job.name:withParamJob}
#      ${job.name:<잡 이름>}job.name 이 없으면 : 뒤에 있는 잡을 실행한다.
#      jobBuilderFactory.get("<잡 이름>") 을 의미

#    --spring.batch.job.names=helloWorldJob 을 입력하여 Application Cofiguration 을 통해 인자값 넘겨줌
    jdbc:
      initialize-schema: ALWAYS
#      spring batch ?? db
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/batch?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    driver-class-name:
    username: lldj
    password: lldj123414
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
logging:
  level:
    com.ll.exam.app_2022_09_22: debug